config/routes.rb
Rails.application.routes.draw do
  get 'investigation/index'
  get 'investigation/show'
  get 'cves/index'
  root to: 'cves#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cve.rb
class Cve < ApplicationRecord
    validates :cve_id, presence: true, uniqueness: true
    validates :source_identifier, presence: true
    validates :published, presence: true
    validates :last_modified, presence: true
    validates :vuln_status, presence: true
    validates :description, presence: true
    validates :cvss_v31_base_score, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
    validates :cvss_v30_base_score, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }, allow_nil: true
    validates :cvss_v2_base_score, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }, allow_nil: true
    validates :weakness, presence: true
    validates :configuration, presence: true
    validate :valid_urls

    private
  
    def valid_urls
      return if reference_urls.all? { |url| url =~ /\A#{URI::regexp(['http', 'https'])}\z/ }
      errors.add(:reference_urls, 'contains invalid url')
    end
    
    require 'net/http'
    require 'json'
    require 'date'
    
    def self.fetch_and_format
    url = 'https://services.nvd.nist.gov/rest/json/cves/2.0/?pubStartDate=2023-06-01T00:00:00.000&pubEndDate=2023-06-12T23:59:59.999' # ここにはNVDのAPI URLを入力します
    uri = URI(url)
    response = Net::HTTP.get(uri)
    data = JSON.parse(response)
    
    formatted_data = data['vulnerabilities'].map do |vulnerability|
      cvss_v31_base_score = vulnerability['cve']['metrics']['cvssMetricV31'][0]['cvssData']['baseScore'] rescue nil
      cvss_v30_base_score = vulnerability['cve']['metrics']['cvssMetricV30'][0]['cvssData']['baseScore'] rescue nil
      cvss_v2_base_score = vulnerability['cve']['metrics']['cvssMetricV2'][0]['cvssData']['baseScore'] rescue nil
      {
        cve_id: vulnerability['cve']['id'],
        source_identifier: vulnerability['cve']['sourceIdentifier'],
        published: vulnerability['cve']['published'],
        last_modified: vulnerability['cve']['lastModified'],
        vuln_status: vulnerability['cve']['vulnStatus'],
        description: vulnerability['cve']['descriptions'][0]['value'],
        cvss_v31_base_score: cvss_v31_base_score,
        cvss_v30_base_score: cvss_v30_base_score,
        cvss_v2_base_score: cvss_v2_base_score,
        weakness: vulnerability['cve']['weaknesses'] ? vulnerability['cve']['weaknesses'][0]['description'][0]['value'] : 'No weakness information available',
        configuration: if vulnerability['cve']['configurations'] && vulnerability['cve']['configurations'][0] && vulnerability['cve']['configurations'][0]['nodes'] && vulnerability['cve']['configurations'][0]['nodes'][0] && vulnerability['cve']['configurations'][0]['nodes'][0]['cpeMatch']
                 cpe_matches = vulnerability['cve']['configurations'][0]['nodes'][0]['cpeMatch']
                 product_names = cpe_matches.map { |cpe| cpe['criteria']&.split(":")&.fetch(3, nil) }.compact.join(", ")
                 product_names.present? ? product_names : 'No configuration information available'
               else
                 'No configuration information available'
               end,
        reference_urls: vulnerability['cve']['references'].map { |ref| ref['url'] }
      }
    end
    
    formatted_data

    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cves_controller.rb
class CvesController < ApplicationController
  def index
    @cves = Cve.fetch_and_format
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/investigation_controller.rb
require 'net/http'
require 'json'
require 'dotenv/load'


class InvestigationController < ApplicationController
  def index
  end

  def show
    ip = params[:ip]
    
    # SHODAN
    api_key = ENV['SHODAN_API_KEY']
    url = "https://api.shodan.io/shodan/host/#{ip}?key=#{api_key}"
    uri = URI(url)
    response = Net::HTTP.get(uri)
    unless response.include?('Invalid IP')
      data = JSON.parse(response)
  
      @shodan_results = {
        ip: data['ip'],
        country_code: data['country_code'],
        latitude: data['latitude'],
        hostnames: hostnames = data['hostnames'][0],
        org: org = data['org'],
        asn: asn = data['asn'],
        isp: isp = data['isp'],
        ports: ports = data['ports'].join(', ')
      }
    else
      @shodan_results = { error: "Request failed with status: #{response.code}" }
    end 
    
    #VirusTotal
    api_key = ENV['VirusTotal_API_KEY']
    url = "https://www.virustotal.com/api/v3/ip_addresses/#{ip}"
    uri = URI(url)
    
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    
    request = Net::HTTP::Get.new(uri)
    request['x-apikey'] = api_key
    
    response = http.request(request)
    if response.code == '200'
      data = JSON.parse(response.body)
      
    @virustotal_results = {
        as_owner: data["data"]["attributes"]["as_owner"],
        asn: data["data"]["attributes"]["asn"],
        country: data["data"]["attributes"]["country"],
        network: data["data"]["attributes"]["network"],
        regional_internet_registry: data["data"]["attributes"]["regional_internet_registry"],
        reputation: data["data"]["attributes"]["reputation"],
      }
    else
      @virustotal_results = { error: "Request failed with status: #{response.code}" }
    end

    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cves_helper.rb
module CvesHelper
    def score_color(score)
      case score
      when 0.0
        'none'
      when 0.1..3.9
        'low'
      when 4.0..6.9
        'medium'
      when 7.0..8.9
        'high'
      when 9.0..10.0
        'critical'
      else
        ''
      end
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/investigation_helper.rb
module InvestigationHelper
end

app/views/cves/index.html.erb
<div id="wrapper">
  <div class="row g-0">
    <!-- サイドバー -->
    <div id="sidebar">
      <div class="vh-100 d-flex flex-column p-3 text-white bg-dark" style="width: 280px; height: 100%;">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
          <span class="fs-4">Osint App</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <a href="/cves/index" class="nav-link active text-white" id="link1" aria-current="page" data-turbo-action="replace" data-turbo-frame="main-content">
              <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
              定常業務
            </a>
          </li>
          <li>
            <a href="/investigation/index" class="nav-link text-white" id="link2" data-turbo-action="replace" data-turbo-frame="main-content">
              <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
              インシデント調査
            </a>
          </li>
        </ul>
        <hr>
      </div>
    </div>

    <!-- メインコンテンツ -->
    <div class="me-1" id="main-content">
      <table class="table table-dark table-hover">
        <thead>
          <tr>
            <th style="width: 200px;">CVE ID</th>
            <th>CVSS</th>
            <th>公開日</th>
            <th>最終更新日</th>
            <th>脆弱性ステータス</th>
            <th>説明</th>
            <th>弱点</th>
            <th>構成</th>
            <th>ソース識別子</th>
            <th>参考文献</th>
          </tr>
        </thead>
        <tbody>
          <% @cves.each do |cve| %>
            <tr>
              <td><%= cve[:cve_id] %></td>
              <td class="<%= score_color(cve[:cvss_v31_base_score]) %>"><%= cve[:cvss_v31_base_score] %></td>
              <td><%= cve[:published].to_time.strftime('%Y/%m/%d') %></td>
              <td><%= cve[:last_modified].to_time.strftime('%Y/%m/%d') %></td>
              <td><%= cve[:vuln_status] %></td>
              <td>
                <button class="toggle-details btn btn-primary" data-id="<%= cve[:cve_id] %>">Show Details</button>
                <div class="description-details" id="<%= cve[:cve_id] %>" style="display: none;"><%= cve[:description] %></div>
                <button class="back-button btn btn-danger" style="display: none;">Back</button>
              </td>
              <td><%= cve[:weakness] %></td>
              <td><%= cve[:configuration] %></td>
              <td><%= cve[:source_identifier] %></td>
              <td>
                <ul>
                  <% cve[:reference_urls]&.each do |ref| %>
                    <li><a href="<%= ref %>"><%= ref %></a></li>
                  <% end %>
                </ul>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= @data %>
<%= @doc %>

app/views/investigation/index.html.erb
<div id="wrapper">
      <div class="row　g-0">
        <!-- サイドバー -->
        <div id="sidebar">
          <div class="vh-100 d-flex flex-column p-3 text-white bg-dark" style="width: 280px; height: 100%;">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
              <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
              <span class="fs-4">Osint App</span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
              <li class="nav-item">
                <a href="/cves/index" class="nav-link text-white" id="link1" aria-current="page" data-turbo-action="replace" data-turbo-frame="main-content">
                  <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                  定常業務
                </a>

              </li>
              <li>
                <a href="investigation/index" class="nav-link active text-white" id="link2" data-turbo-action="replace" data-turbo-frame="main-content">
                  <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
                  インシデント調査
                </a>
              </li>
            </ul>
            <hr>
          </div>
        </div>

        </div>
        <!-- メインコンテンツ -->
    　<div class="me-1" id="main-content">
    　   <div class="card text-center">
          <div class="card-header">
            IPaddress
          </div>
          <div class="card-body">
            <h5 class="card-title">Search For IPaddress</h5>
            <%= form_tag(investigation_show_path, method: :get) do %>
              <p class="card-text">
                <%= label_tag :ip, "IP Address:" %>
                <%= text_field_tag :ip, params[:ip] %>
              </p>
              <%= submit_tag "Search", class: "btn btn-primary" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
          </div>
        </div>
      </div>
    </div>

app/views/investigation/show.html.erb
<div id="wrapper">
      <div class="row　g-0">
        <!-- サイドバー -->
        <div id="sidebar">
          <div class="vh-100 d-flex flex-column p-3 text-white bg-dark" style="width: 280px; height: 100%;">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
              <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
              <span class="fs-4">Osint App</span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
              <li class="nav-item">
                <a href="/cves/index" class="nav-link text-white" id="link1" aria-current="page" data-turbo-action="replace" data-turbo-frame="main-content">
                  <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                  定常業務
                </a>

              </li>
              <li>
                <a href="investigation/index" class="nav-link active text-white" id="link2" data-turbo-action="replace" data-turbo-frame="main-content">
                  <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
                  インシデント調査
                </a>
              </li>
            </ul>
            <hr>
          </div>
        </div>
        </div>
        <!-- メインコンテンツ -->
        <div class="me-1" id="main-content">
            <div class="card text-center">
              <div class="card-header">
                SHODAN
              </div>
              <div class="card-body">
                <h5 class="card-title">SHODAN's Results</h5>
                <div class="card-text">
            <table class="table table-dark table-hover">
              <thead>
                <tr>
                  <% @shodan_results.keys.each do |key| %>
                    <th scope="col"><%= key.capitalize %></th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <% @shodan_results.values.each do |value| %>
                    <td><%= value %></td>
                  <% end %>
                </tr>
              </tbody>
            </table>
            </div>
              </div>
              <div class="card-footer text-muted">
                SHODAN
              </div>
            </div>
            <div style="height: 20px;"></div>
            <div class="card text-center">
              <div class="card-header">
                VirusTotal
              </div>
              <div class="card-body">
                <h5 class="card-title">VirusTotal's Results</h5>
                <div class="card-text">
            <table class="table table-dark table-hover">
              <thead>
                <tr>
                  <% @virustotal_results.keys.each do |key| %>
                    <th scope="col"><%= key.capitalize %></th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <% @virustotal_results.values.each do |value| %>
                    <td><%= value %></td>
                  <% end %>
                </tr>
              </tbody>
            </table>
            </div>
              </div>
              <div class="card-footer text-muted">
                VirusTotal
              </div>
            </div>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Osint</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag "/osint/app/assets/stylesheets/application.bootstrap.scss", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%#= javascript_include_tag "/osint/app/assets/config/manifest.js", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>